site_name: Deep Robotics Knowledge Base

nav:
- Главная (overview от Юры): 'index.md'
- Элективы по истории: 'electives.md'
- Преподаватели: 'teachers.md'
- 1 курс:
  - Матанализ (1 семестр):
    - Лекции:
      - Лекция 1: 'grade-1/math-lectures-sem-1/mathlecture1-1.md'
      - Лекция 2: 'grade-1/math-lectures-sem-1/mathlecture1-2.md'
      - Лекция 3: 'grade-1/math-lectures-sem-1/mathlecture1-3.md'
      - Лекция 4: 'grade-1/math-lectures-sem-1/mathlecture1-4.md'
      - Лекция 5: 'grade-1/math-lectures-sem-1/mathlecture1-5.md'
      - Лекция 6: 'grade-1/math-lectures-sem-1/mathlecture1-6.md'
      - Лекция 7: 'grade-1/math-lectures-sem-1/mathlecture1-7.md'
      - Лекция 8: 'grade-1/math-lectures-sem-1/mathlecture1-8.md'
      - Лекция 9: 'grade-1/math-lectures-sem-1/mathlecture1-9.md'
      - Лекция 10: 'grade-1/math-lectures-sem-1/mathlecture1-10.md'
      - Лекция 11: 'grade-1/math-lectures-sem-1/mathlecture1-11.md'
      - Лекция 12: 'grade-1/math-lectures-sem-1/mathlecture1-12.md'
      - Лекция 13: 'grade-1/math-lectures-sem-1/mathlecture1-13.md'
      - Лекция 14: 'grade-1/math-lectures-sem-1/mathlecture1-14.md'
    - Разбор определений к экзамену (2022-2023): 'grade-1/math-exam-sem-1.md'
  - Матанализ (2 семестр):
    - Разбор определений к экзамену (2023-2024): 'grade-1/math-exam-sem-2-2024.md'
    - Разбор определений к экзамену (2022-2023): 'grade-1/math-exam-sem-2.md'
  - Дискретная математика (семестр 1):
    - Разбор билетов (2022-2023): 'grade-1/discrete-exam-sem-1.md'
  - Дискретная математика (семестр 2):
    - Разбор билетов (2022-2023): 'grade-1/discrete-exam-sem-2.md'
  - Цифровые платформы (Logisim):
    - Классический Logisim станет гораздо мощнее — он получит функционал… (Введение в Logisim): 'grade-1/logisim-introduction.md'
    - Я проснулся и открыл Logisim (Описание библиотек): 'grade-1/i-woke-up-and-opened-logisim.md'
    - Гайд по подключению процессора (для проекта): 'grade-1/processor-implementation.md'
    - Гайд по программированию на "ассемблере": 'grade-1/digital-platforms-programming.md'
  - Императивное программирование:
    - Гайд по проектам: 'grade-1/programming-project.md'
- 2 курс:
  - Инж. графика:
    - КОМПАС-3D на Linux. Невозможно?: 'grade-2/kompas-on-linux.md'
  - Методы алгебры и анализа:
    - Контрольные работы (Мальковича, 2024): 'grade-2/algebraic-methods-tests.md'
  # - Теория вероятности и мат. статистика:
  #   - Обучающие материалы и задания: 'math-stat-2024.md'
- 3 курс:
  - Введение в 6й семестр (2025): 'grade-3/sem-6-intro.md'

exclude_docs: |
  math-stat-2024.md

theme:
  name: material
  locale: ru
  include_sidebar: true
  custom_dir: overrides

docs_dir: docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde # strikethrough text support

#  - toc:
#      baselevel: 4

extra_javascript:
  - javascripts/mathjax.js # LaTeX markup support
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # LaTeX markup support
